/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pricey1600 (https://sketchfab.com/Pricey1600)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cardboard-box-4e622ef1a09c43e28a49d9fa37f9eeee
Title: Cardboard Box
*/

import React from "react";
import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import dataBox from "../assets/3d/cardboard_box.glb"

export function Box({ isRotating, ...props }) {
  const ref = useRef();
  const { nodes, materials, scene, animations  } = useGLTF(dataBox);

   const { actions } = useAnimations(animations, ref);



  return (
    <group {...props} dispose={null}>
      <mesh  {...props} ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.CardboardBox_LP_lambert1_0.geometry}
        material={materials.lambert1}
        scale={0.25}
      />
     </group>
  );
}

useGLTF.preload(dataBox);
