/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pinos (https://sketchfab.com/PauloWardson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steel-warehouse-201cf5b39e9040e7adba3111e558416e
Title: Steel Warehouse
*/
import { a } from "@react-spring/three";
import { useEffect } from "react";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import models from "../assets/3d/steel_warehouse.glb"
import { Table } from "./table";
import { Box } from "./Box";

export function TestWarehouses({isRotating,
  setIsRotating,
  setCurrentStage,
  currentFocusPoint,
  ...props}) {
    const islandRef = useRef();
    const { gl, viewport, camera } = useThree();
  const { nodes, materials } = useGLTF(models);


const{islandPosition, islandScale, biplaneScale, biplanePosition } =props;
// Use a ref for the last mouse x position
const lastX = useRef(0);
// Use a ref for rotation speed
const rotationSpeed = useRef(0);
// Define a damping factor to control rotation damping
const dampingFactor = 0.95;

// Handle pointer (mouse or touch) down event
const handlePointerDown = (event) => {
  event.stopPropagation();
  event.preventDefault();
  setIsRotating(true);

  // Calculate the clientX based on whether it's a touch event or a mouse event
  const clientX = event.touches ? event.touches[0].clientX : event.clientX;

  // Store the current clientX position for reference
  lastX.current = clientX;
};

// Handle pointer (mouse or touch) up event
const handlePointerUp = (event) => {
  event.stopPropagation();
  event.preventDefault();
  setIsRotating(false);
};

// Handle pointer (mouse or touch) move event
const handlePointerMove = (event) => {
  event.stopPropagation();
  event.preventDefault();
  if (isRotating) {
    // If rotation is enabled, calculate the change in clientX position
    const clientX = event.touches ? event.touches[0].clientX : event.clientX;

    // calculate the change in the horizontal position of the mouse cursor or touch input,
    // relative to the viewport's width
    const delta = (clientX - lastX.current) / viewport.width;

    // Update the island's rotation based on the mouse/touch movement
    islandRef.current.rotation.y += delta * 0.01 * Math.PI;

    // Update the reference for the last clientX position
    lastX.current = clientX;

    // Update the rotation speed
    rotationSpeed.current = delta * 0.01 * Math.PI;
  }
};

// Handle keydown events
const handleKeyDown = (event) => {

  if (event.key === "ArrowLeft") {
    if (!isRotating) setIsRotating(true);

    islandRef.current.rotation.y += 0.005 * Math.PI;
    rotationSpeed.current = 0.007;
  } else if (event.key === "ArrowRight") {
    if (!isRotating) setIsRotating(true);

    islandRef.current.rotation.y -= 0.005 * Math.PI;
    rotationSpeed.current = -0.007;
  }
};

// Handle keyup events
const handleKeyUp = (event) => {
  if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
    setIsRotating(false);
  }
};

 // Handle keyup events
const onMouseWheel = (event) => {
  event.preventDefault();

  // Zoom in or out based on scroll direction
  const delta = event.deltaY > 0 ? 1 : -1;
  camera.position.z += delta;

  // Render the scene
  renderer.render(scene, camera);
};

useEffect(() => {
  // Add event listeners for pointer and keyboard events
  const canvas = gl.domElement;
  canvas.addEventListener("pointerdown", handlePointerDown);
  canvas.addEventListener("pointerup", handlePointerUp);
  canvas.addEventListener("pointermove", handlePointerMove);
  window.addEventListener("keydown", handleKeyDown);
  window.addEventListener("keyup", handleKeyUp);
  window.addEventListener("wheel", onMouseWheel);

  // Remove event listeners when component unmounts
  return () => {
    canvas.removeEventListener("pointerdown", handlePointerDown);
    canvas.removeEventListener("pointerup", handlePointerUp);
    canvas.removeEventListener("pointermove", handlePointerMove);
    window.removeEventListener("keydown", handleKeyDown);
    window.removeEventListener("keyup", handleKeyUp);
    window.removeEventListener("wheel", onMouseWheel);
  };
}, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

// This function is called on each frame update
useFrame(() => {
  // If not rotating, apply damping to slow down the rotation (smoothly)
  if (!isRotating) {
    // Apply damping factor
    rotationSpeed.current *= dampingFactor;

    // Stop rotation when speed is very small
    if (Math.abs(rotationSpeed.current) < 0.001) {
      rotationSpeed.current = 0;
    }

    islandRef.current.rotation.y += rotationSpeed.current;
  } else {
    // When rotating, determine the current stage based on island's orientation
    const rotation = islandRef.current.rotation.y;

    /**
     * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
     * The goal is to ensure that the rotation value remains within a specific range to
     * prevent potential issues with very large or negative rotation values.
     *  Here's a step-by-step explanation of what this code does:
     *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
     *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
     *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
     *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
     *     This is done to ensure that the value remains positive and within the range of
     *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
     *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
     *     modulo operation to the value obtained in step 2. This step guarantees that the value
     *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
     *     circle in radians.
     */
    const normalizedRotation =
      ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    // Set the current stage based on the island's orientation
    switch (true) {
      case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
        setCurrentStage(4);
        break;
      case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
        setCurrentStage(3);
        break;
      case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
        setCurrentStage(2);
        break;
      case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
        setCurrentStage(1);
        break;
      default:
        setCurrentStage(null);
    }
  }
});

  return (
    <a.group ref={islandRef} {...props} dispose={null}>
      <group scale={0.1}>
        <Table
            isRotating={isRotating}
            setIsRotating={setIsRotating}
            setCurrentStage={setCurrentStage}
            position={[0, 0, -200]}
            rotation={[0, 0, 0]}
            scale={biplaneScale}
          />
          <Box
            isRotating={isRotating}
            position={[20, 67, 10]}
            rotation={[0, 0, 0]}
            scale={[2, 2, -2]}
          />
          <Box
            isRotating={isRotating}
            position={[3, 67, 110]}
            rotation={[0, 0, 0]}
            scale={[1, 2, -2]}
          />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["steelWarehouse-Metalroof001_warehouseMetalroof_0"].geometry
          }
          material={materials.warehouseMetalroof}
          position={[-329.676, 512.29, -699.989]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <Table
            isRotating={isRotating}
            setIsRotating={setIsRotating}
            setCurrentStage={setCurrentStage}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[0, 0, 0]}
          />
          <Table
            isRotating={isRotating}
            setIsRotating={setIsRotating}
            setCurrentStage={setCurrentStage}
            position={[0, 0, -100]}
            rotation={[0, 0, 0]}
            scale={[0, 0, 0]}
          />
         
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams002_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-666.633, 201.805, -112.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams001_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-353.102, 480.795, -112.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams003_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[341.766, 483.595, -112.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[666.633, 201.805, -112.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars_bars_0.geometry}
          material={materials.bars}
          position={[-683.851, 165.067, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-475.337, 198.794, 93.221]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls001_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-350, 205.514, -1491.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls004_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[124.285, 474.597, 92.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls005_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[474.68, 431.748, 92.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls006_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-474.285, 431.761, 93.051]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls007_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[475.206, 211.54, 92.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls008_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-233.333, 468.229, -1491.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls009_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[233.333, 468.229, -1491.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls010_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[350, 205.514, -1491.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls013_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 58.799, -451.614]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls014_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 160.783, -719.058]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls015_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 160.783, -149.897]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls016_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 307.498, -451.614]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls017_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 307.498, -986.503]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls018_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 58.799, -986.503]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls019_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 160.783, -1269.161]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls020_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 307.498, -149.897]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls021_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 307.498, -719.058]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls022_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 307.498, -1269.161]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls023_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 58.799, -1269.161]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls024_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 58.799, -719.058]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls025_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[692.437, 58.799, -149.897]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls026_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 307.498, -986.503]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls027_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 307.498, -451.614]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls028_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 58.799, -451.614]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls029_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 58.799, -986.503]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls030_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 160.783, -719.058]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls031_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 160.783, -1269.161]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls032_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 160.783, -149.897]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls033_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 307.498, -1269.161]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls034_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 307.498, -719.058]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls035_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 307.498, -149.897]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls036_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 58.799, -149.897]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls037_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 58.799, -719.058]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls038_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-692.437, 58.799, -1269.161]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["steelWarehouse-Metalroof_warehouseMetalroof_0"].geometry
          }
          material={materials.warehouseMetalroof}
          position={[329.516, 512.012, -699.989]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars001_bars_0.geometry}
          material={materials.bars}
          position={[-683.851, 246.279, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars002_bars_0.geometry}
          material={materials.bars}
          position={[-683.851, 83.855, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars003_bars_0.geometry}
          material={materials.bars}
          position={[-0.665, 246.279, -1480.953]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars004_bars_0.geometry}
          material={materials.bars}
          position={[-0.665, 83.855, -1480.953]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars005_bars_0.geometry}
          material={materials.bars}
          position={[-467.782, 246.279, 85.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars006_bars_0.geometry}
          material={materials.bars}
          position={[-467.782, 83.855, 85.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars007_bars_0.geometry}
          material={materials.bars}
          position={[466.451, 246.279, 85.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars008_bars_0.geometry}
          material={materials.bars}
          position={[332.814, 83.855, 85.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars009_bars_0.geometry}
          material={materials.bars}
          position={[608.802, 83.855, 85.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars010_bars_0.geometry}
          material={materials.bars}
          position={[684.001, 246.279, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars011_bars_0.geometry}
          material={materials.bars}
          position={[684.001, 83.855, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars012_bars_0.geometry}
          material={materials.bars}
          position={[600.044, 433.7, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars013_bars_0.geometry}
          material={materials.bars}
          position={[499.951, 458.445, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars014_bars_0.geometry}
          material={materials.bars}
          position={[399.859, 482.078, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars015_bars_0.geometry}
          material={materials.bars}
          position={[300.099, 506.545, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars016_bars_0.geometry}
          material={materials.bars}
          position={[200.007, 530.734, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars017_bars_0.geometry}
          material={materials.bars}
          position={[100.074, 556.033, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars018_bars_0.geometry}
          material={materials.bars}
          position={[9.911, 578.623, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars019_bars_0.geometry}
          material={materials.bars}
          position={[-9.933, 578.623, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars020_bars_0.geometry}
          material={materials.bars}
          position={[-99.766, 555.986, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars021_bars_0.geometry}
          material={materials.bars}
          position={[-199.959, 531.443, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars022_bars_0.geometry}
          material={materials.bars}
          position={[-299.799, 506.423, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars023_bars_0.geometry}
          material={materials.bars}
          position={[-399.855, 482.118, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars024_bars_0.geometry}
          material={materials.bars}
          position={[-499.911, 457.794, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.metallicBars025_bars_0.geometry}
          material={materials.bars}
          position={[-600.447, 433.489, -693.432]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelGate001_steelWarehouse-gate&beams_0"].geometry}
          material={materials["steelWarehouse-gatebeams"]}
          position={[0, 391.275, 92.744]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelGate002_steelWarehouse-gate&beams_0"].geometry}
          material={materials["steelWarehouse-gatebeams"]}
          position={[243.812, 213.903, 92.744]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelGate003_steelWarehouse-gate&beams_0"].geometry}
          material={materials["steelWarehouse-gatebeams"]}
          position={[-244.165, 217.163, 92.744]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams004_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-666.633, 201.805, -512.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams005_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-353.102, 480.795, -512.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams006_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[341.766, 483.595, -512.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams007_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[666.633, 201.805, -512.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams008_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-666.633, 201.805, -912.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams009_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-353.102, 480.795, -912.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams010_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[341.766, 483.595, -912.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams011_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[666.633, 201.805, -912.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams012_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-666.633, 201.805, -1312.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams013_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[-353.102, 480.795, -1312.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams014_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[341.766, 483.595, -1312.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ceilingBeams015_Warehouse-ceilingBeams_0"].geometry}
          material={materials["Warehouse-ceilingBeams"]}
          position={[666.633, 201.805, -1312.263]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["steelWarehouse-Walls039_steelWarehouse_0"].geometry}
          material={materials.steelWarehouse}
          position={[-124.285, 474.597, 93.051]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "simpleDoor-by-Pinos-on-Sketchfab_simpleDoor-by-Pinos-on-Sketchfab_0"
            ].geometry
          }
          material={materials["simpleDoor-by-Pinos-on-Sketchfab"]}
          position={[451.827, 111.868, 90.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "simpleWindow-by-Pinos-on-Sketchfab002_simpleWindow-by-Pinos-on-Sketchfab_0"
            ].geometry
          }
          material={materials["simpleWindow-by-Pinos-on-Sketchfab"]}
          position={[691.863, 159.117, -986.493]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "simpleWindow-by-Pinos-on-Sketchfab_simpleWindow-by-Pinos-on-Sketchfab_0"
            ].geometry
          }
          material={materials["simpleWindow-by-Pinos-on-Sketchfab"]}
          position={[691.863, 159.117, -451.89]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "simpleWindow-by-Pinos-on-Sketchfab003_simpleWindow-by-Pinos-on-Sketchfab_0"
            ].geometry
          }
          material={materials["simpleWindow-by-Pinos-on-Sketchfab"]}
          position={[-692.452, 159.117, -451.879]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "simpleWindow-by-Pinos-on-Sketchfab004_simpleWindow-by-Pinos-on-Sketchfab_0"
            ].geometry
          }
          material={materials["simpleWindow-by-Pinos-on-Sketchfab"]}
          position={[-692.452, 159.117, -986.768]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ironBeams_steelWarehouse-gate&beams_0"].geometry}
          material={materials["steelWarehouse-gatebeams"]}
          position={[694.205, 208.402, 95.138]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ironBeams001_steelWarehouse-gate&beams_0"].geometry}
          material={materials["steelWarehouse-gatebeams"]}
          position={[694.205, 208.402, -1488.82]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ironBeams003_steelWarehouse-gate&beams_0"].geometry}
          material={materials["steelWarehouse-gatebeams"]}
          position={[-688.527, 208.402, 95.138]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ironBeams002_steelWarehouse-gate&beams_0"].geometry}
          material={materials["steelWarehouse-gatebeams"]}
          position={[-688.527, 208.402, -1488.113]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </a.group>
  );
}

useGLTF.preload(models);
